In [1]:
import sys
import numpy as np

Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

Array Types

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int32')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [18]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [19]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [20]:
c = np.array(['a', 'b', 'c'])

In [21]:
c.dtype

dtype('<U1')

In [22]:
d = np.array([{'a': 1}, sys])

In [23]:
d.dtype

dtype('O')

Dimensions and shapes

In [24]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [25]:
A.shape

(2, 3)

In [26]:
A.ndim

2

In [27]:
A.size

6

In [28]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [30]:
B


array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [31]:
B.shape

(2, 2, 3)

In [32]:
B.ndim

3

In [33]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:



In [34]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [35]:
C.dtype

dtype('O')

In [36]:
C.shape

(2,)

In [37]:
C.size

2

In [38]:
type(C[0])

list

Indexing and Slicing of Matrices

In [39]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [40]:
A[1]

array([4, 5, 6])

In [41]:
A[1][0]

4

In [42]:
A[1, 0]

4

In [43]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [45]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [46]:
A[:2, 2:]

array([[3],
       [6]])

In [47]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
A[1] = np.array([10, 10, 10])

In [49]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [50]:
A[2] = 99

In [51]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

Summary statistics

In [52]:
a = np.array([1, 2, 3, 4])

In [53]:
a.sum()

10

In [54]:
a.mean()

2.5

In [55]:
a.std()

1.118033988749895

In [56]:
a.var()

1.25

In [57]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [58]:
A.sum()

45

In [59]:
A.mean()

5.0

In [60]:
A.std()

2.581988897471611

In [61]:
A.sum(axis=0)

array([12, 15, 18])

In [62]:
A.sum(axis=1)

array([ 6, 15, 24])

In [63]:
A.mean(axis=0)

array([4., 5., 6.])

In [64]:
A.mean(axis=1)

array([2., 5., 8.])

In [65]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [66]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

Broadcasting and Vectorized operations


In [67]:
a = np.arange(4)

In [68]:
a

array([0, 1, 2, 3])

In [69]:
a + 10

array([10, 11, 12, 13])

In [70]:
a * 10

array([ 0, 10, 20, 30])

In [71]:
a

array([0, 1, 2, 3])

In [72]:
a += 100

In [73]:
a

array([100, 101, 102, 103])

In [74]:
l = [0, 1, 2, 3]

In [75]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [76]:
a = np.arange(4)

In [78]:
a

array([0, 1, 2, 3])

In [79]:
b = np.array([10, 10, 10, 10])

In [80]:
b

array([10, 10, 10, 10])

In [81]:
a + b

array([10, 11, 12, 13])

In [82]:
a * b

array([ 0, 10, 20, 30])

Boolean arrays

In [83]:
a = np.arange(4)

In [84]:
a

array([0, 1, 2, 3])

In [85]:
a[0], a[-1]

(0, 3)

In [86]:
a[[0, -1]]

array([0, 3])

In [87]:
a[[True, False, False, True]]

array([0, 3])

In [88]:
a

array([0, 1, 2, 3])

In [89]:
a >= 2

array([False, False,  True,  True])

In [90]:
a[a >= 2]

array([2, 3])

In [91]:
a.mean()

1.5

In [92]:
a[a > a.mean()]

array([2, 3])

In [93]:
a[~(a > a.mean())]

array([0, 1])

In [94]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [95]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [97]:
A = np.random.randint(100, size=(3, 3))

In [98]:
A

array([[44, 90, 48],
       [36, 13, 92],
       [52,  3, 79]])

In [99]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([44, 48, 13, 52, 79])

In [100]:
A > 30

array([[ True,  True,  True],
       [ True, False,  True],
       [ True, False,  True]])

In [101]:
A[A > 30]

array([44, 90, 48, 36, 92, 52, 79])

Linear Algebra

In [102]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [103]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [104]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [105]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [106]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [107]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

Size of objects in Memory

In [109]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [110]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [111]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [112]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [113]:
np.dtype(float).itemsize

8

In [114]:
# A one-element list
sys.getsizeof([1])

72

In [115]:
# An array of one element in numpy
np.array([1]).nbytes

4

 And performance is also important


In [116]:
l = list(range(100000))

In [117]:
a = np.arange(100000)

In [118]:
%time np.sum(a ** 2)

Wall time: 964 µs


216474736

In [119]:
%time sum([x ** 2 for x in l])

Wall time: 39 ms


333328333350000

Useful Numpy functions


random

In [121]:
np.random.random(size=2)

array([0.88529333, 0.10987637])

In [122]:
np.random.normal(size=2)

array([0.41704501, 0.24456912])

In [123]:
np.random.rand(2, 4)

array([[0.59571062, 0.76917447, 0.53024491, 0.55416458],
       [0.06141916, 0.72231566, 0.36570384, 0.59919331]])

arange

In [124]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [126]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

reshape

In [127]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [128]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

linspace

In [129]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [130]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [131]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

zeros, ones, empty

In [133]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [134]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [136]:
np.zeros((3, 3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [137]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [138]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [139]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [140]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

identity and eye

In [141]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [142]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [143]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [144]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [145]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [146]:
"Hello World"[6]

'W'